### ISSUE TITLE
Copy button doesn't work anymore

### ISSUE THREAD

**Issue by StijnCaerts** [MidasLamb/CSSchedule#19]

**Comment by MidasLamb** [comment]
I think it was because no courses were selected?

**Comment by StijnCaerts** [comment]
No, at least in the current live version it doesn't work when you have courses selected...

**Comment by MidasLamb** [comment]
Doesn't work live but works locally for me

**Comment by StijnCaerts** [comment]
Ok, will test latest version locally!

**Comment by StijnCaerts** [comment]
Doesn't work for me when the linkSelector is set to 'display: none'

**Comment by MidasLamb** [comment]
Found a fix, currently implementing it
