### ISSUE TITLE
Update the public site to the latest commit

### ISSUE THREAD

**Issue by timower** [MidasLamb/CSSchedule#45]
When visiting the website csschedule.xyz I still don't get the schedule for 2018-2019.

**Comment by MidasLamb** [comment]
We're looking into moving to a new domain name (since i'm cheap and don't want to spend €10). To prevent users from using the link for their calendar (instead of downloading), the update is postponed till after the move to the new domain name.

**Comment by MidasLamb** [comment]
@timower [the app](https://cs-schedule.herokuapp.com/) is live now
