### ISSUE TITLE
Update schedule for 19-20

### ISSUE THREAD

**Issue by jelle-dc** [MidasLamb/CSSchedule#61]
the website currently only shows schedules for 2018-2019

**Comment by RobinVanhove** [comment]
Wat is juist het probleem?

**Comment by marnikow** [comment]
Volgens mij moet de cronjob uitgevoerd worden zodat de db geüpdate wordt

**Comment by StijnCaerts** [comment]
Database is geüpdatet.
CSSchedule is te raadplegen via [http://cs-schedule.herokuapp.com/](http://cs-schedule.herokuapp.com/).
