### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by MidasLamb** [MidasLamb/CSSchedule#8]

**Comment by StijnCaerts** [comment]
I want to do this!

**Comment by MidasLamb** [comment]
Idea: use [these type of checkboxes](https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons)

**Comment by StijnCaerts** [comment]
Problem with these checkboxes is that the checkbox itself isn't clicked, the button is clicked and will set the state of the checkbow. So `onclick` won't work on the `<input>` tag.

**Comment by StijnCaerts** [comment]
Found a way to overcome this problem

**Comment by MidasLamb** [comment]
I think we can consider this done.
